// ============================================================
// H4KKEN - Move Data Table
// ============================================================

import { HIT_RESULT } from '../constants';
import { LEVEL, type MoveData } from './types';

export const MOVES: Record<string, MoveData> = {
  // ========== STANDING ATTACKS ==========

  // Left Punch - fast jab, high
  lp: {
    name: 'Left Punch',
    command: 'lp',
    inputDir: null,
    level: LEVEL.HIGH,
    damage: 12,
    chipDamage: 1,
    startupFrames: 10,
    activeFrames: 3,
    recoveryFrames: 11,
    hitstun: 18,
    blockstun: 10,
    onHit: HIT_RESULT.STAGGER,
    pushback: 0.15,
    pushbackOnBlock: 0.2,
    animation: 'punch1',
    animSpeed: 1.3,
    hitboxOffset: { x: 0.7, y: 1.4, z: 0 },
    hitboxSize: { x: 0.4, y: 0.3, z: 0.4 },
    comboRoutes: ['rp', 'lk'],
    canChainFrom: [],
  },

  // Right Punch - straight, high, more damage
  rp: {
    name: 'Right Punch',
    command: 'rp',
    inputDir: null,
    level: LEVEL.HIGH,
    damage: 16,
    chipDamage: 2,
    startupFrames: 14,
    activeFrames: 3,
    recoveryFrames: 14,
    hitstun: 22,
    blockstun: 12,
    onHit: HIT_RESULT.STAGGER,
    pushback: 0.25,
    pushbackOnBlock: 0.3,
    animation: 'punch2',
    animSpeed: 1.2,
    hitboxOffset: { x: 0.8, y: 1.4, z: 0 },
    hitboxSize: { x: 0.45, y: 0.35, z: 0.4 },
    comboRoutes: ['lk', 'rk'],
    canChainFrom: ['lp'],
  },

  // Forward + LP - Body Blow, mid
  f_lp: {
    name: 'Body Blow',
    command: 'lp',
    inputDir: 'forward',
    level: LEVEL.MID,
    damage: 18,
    chipDamage: 2,
    startupFrames: 16,
    activeFrames: 4,
    recoveryFrames: 16,
    hitstun: 24,
    blockstun: 14,
    onHit: HIT_RESULT.KNOCKBACK,
    pushback: 0.35,
    pushbackOnBlock: 0.4,
    animation: 'punch1',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.7, y: 1.1, z: 0 },
    hitboxSize: { x: 0.5, y: 0.4, z: 0.5 },
    comboRoutes: ['rp'],
    canChainFrom: [],
    forwardLunge: 0.04,
  },

  // Forward + RP - Power Straight, mid
  f_rp: {
    name: 'Power Straight',
    command: 'rp',
    inputDir: 'forward',
    level: LEVEL.MID,
    damage: 24,
    chipDamage: 3,
    startupFrames: 20,
    activeFrames: 4,
    recoveryFrames: 20,
    hitstun: 28,
    blockstun: 16,
    onHit: HIT_RESULT.KNOCKBACK,
    pushback: 0.45,
    pushbackOnBlock: 0.5,
    animation: 'heavyPunch',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.9, y: 1.3, z: 0 },
    hitboxSize: { x: 0.5, y: 0.4, z: 0.5 },
    comboRoutes: [],
    canChainFrom: [],
    forwardLunge: 0.05,
  },

  // Down-Forward + RP - Launcher Uppercut
  df_rp: {
    name: 'Launcher',
    command: 'rp',
    inputDir: 'df',
    level: LEVEL.MID,
    damage: 20,
    chipDamage: 3,
    startupFrames: 16,
    activeFrames: 4,
    recoveryFrames: 26,
    hitstun: 40,
    blockstun: 18,
    onHit: HIT_RESULT.LAUNCH,
    launchVelocity: 0.32,
    pushback: 0.15,
    pushbackOnBlock: 0.4,
    animation: 'meleeUppercut',
    animSpeed: 1.1,
    hitboxOffset: { x: 0.7, y: 1.5, z: 0 },
    hitboxSize: { x: 0.5, y: 0.5, z: 0.5 },
    comboRoutes: [],
    canChainFrom: [],
    forwardLunge: 0.03,
  },

  // Down + RP - Uppercut from crouch, mid
  d_rp: {
    name: 'Rising Upper',
    command: 'rp',
    inputDir: 'down',
    level: LEVEL.MID,
    damage: 22,
    chipDamage: 3,
    startupFrames: 15,
    activeFrames: 4,
    recoveryFrames: 24,
    hitstun: 35,
    blockstun: 16,
    onHit: HIT_RESULT.LAUNCH,
    launchVelocity: 0.28,
    pushback: 0.1,
    pushbackOnBlock: 0.35,
    animation: 'meleeUppercut',
    animSpeed: 1.2,
    hitboxOffset: { x: 0.6, y: 1.6, z: 0 },
    hitboxSize: { x: 0.4, y: 0.5, z: 0.4 },
    comboRoutes: [],
    canChainFrom: [],
    requiresCrouch: true,
  },

  // Left Kick - mid
  lk: {
    name: 'Left Kick',
    command: 'lk',
    inputDir: null,
    level: LEVEL.MID,
    damage: 14,
    chipDamage: 2,
    startupFrames: 13,
    activeFrames: 3,
    recoveryFrames: 14,
    hitstun: 20,
    blockstun: 12,
    onHit: HIT_RESULT.STAGGER,
    pushback: 0.2,
    pushbackOnBlock: 0.25,
    animation: 'kickRight',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.8, y: 0.9, z: 0 },
    hitboxSize: { x: 0.5, y: 0.35, z: 0.5 },
    comboRoutes: ['rk', 'rp'],
    canChainFrom: ['lp', 'rp'],
  },

  // Right Kick - mid, slower, more powerful
  rk: {
    name: 'Right Kick',
    command: 'rk',
    inputDir: null,
    level: LEVEL.MID,
    damage: 20,
    chipDamage: 3,
    startupFrames: 18,
    activeFrames: 4,
    recoveryFrames: 18,
    hitstun: 26,
    blockstun: 14,
    onHit: HIT_RESULT.KNOCKBACK,
    pushback: 0.35,
    pushbackOnBlock: 0.4,
    animation: 'kickLeft',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.9, y: 0.8, z: 0 },
    hitboxSize: { x: 0.5, y: 0.4, z: 0.5 },
    comboRoutes: [],
    canChainFrom: ['lk'],
  },

  // Down + LK - Low kick
  d_lk: {
    name: 'Low Kick',
    command: 'lk',
    inputDir: 'down',
    level: LEVEL.LOW,
    damage: 10,
    chipDamage: 1,
    startupFrames: 12,
    activeFrames: 3,
    recoveryFrames: 14,
    hitstun: 16,
    blockstun: 10,
    onHit: HIT_RESULT.STAGGER,
    pushback: 0.1,
    pushbackOnBlock: 0.15,
    animation: 'lowKick',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.7, y: 0.3, z: 0 },
    hitboxSize: { x: 0.5, y: 0.3, z: 0.5 },
    comboRoutes: ['d_rk'],
    canChainFrom: [],
    requiresCrouch: true,
  },

  // Down + RK - Sweep, low, knockdown
  d_rk: {
    name: 'Sweep',
    command: 'rk',
    inputDir: 'down',
    level: LEVEL.LOW,
    damage: 18,
    chipDamage: 2,
    startupFrames: 20,
    activeFrames: 4,
    recoveryFrames: 28,
    hitstun: 30,
    blockstun: 18,
    onHit: HIT_RESULT.KNOCKDOWN,
    pushback: 0.2,
    pushbackOnBlock: 0.3,
    animation: 'sweepKick',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.8, y: 0.2, z: 0 },
    hitboxSize: { x: 0.6, y: 0.3, z: 0.6 },
    comboRoutes: [],
    canChainFrom: ['d_lk'],
    requiresCrouch: true,
  },

  // Down + LP - Crouch Jab, low
  d_lp: {
    name: 'Crouch Jab',
    command: 'lp',
    inputDir: 'down',
    level: LEVEL.LOW,
    damage: 8,
    chipDamage: 1,
    startupFrames: 10,
    activeFrames: 3,
    recoveryFrames: 12,
    hitstun: 14,
    blockstun: 8,
    onHit: HIT_RESULT.STAGGER,
    pushback: 0.1,
    pushbackOnBlock: 0.12,
    animation: 'punch1',
    animSpeed: 1.4,
    hitboxOffset: { x: 0.6, y: 0.5, z: 0 },
    hitboxSize: { x: 0.4, y: 0.3, z: 0.4 },
    comboRoutes: ['d_rp', 'd_lk'],
    canChainFrom: [],
    requiresCrouch: true,
  },

  // Heavy Punch - big power move
  heavy: {
    name: 'Hammer Fist',
    command: 'rp',
    inputDir: null,
    isHeavy: true,
    level: LEVEL.MID,
    damage: 30,
    chipDamage: 5,
    startupFrames: 24,
    activeFrames: 5,
    recoveryFrames: 24,
    hitstun: 35,
    blockstun: 20,
    onHit: HIT_RESULT.CRUMPLE,
    pushback: 0.4,
    pushbackOnBlock: 0.5,
    animation: 'heavyPunch',
    animSpeed: 0.85,
    hitboxOffset: { x: 0.8, y: 1.3, z: 0 },
    hitboxSize: { x: 0.6, y: 0.5, z: 0.5 },
    comboRoutes: [],
    canChainFrom: [],
    forwardLunge: 0.03,
  },

  // Throw (LP + LK)
  throw_cmd: {
    name: 'Throw',
    command: 'throw',
    inputDir: null,
    level: LEVEL.THROW,
    damage: 35,
    chipDamage: 0,
    startupFrames: 12,
    activeFrames: 3,
    recoveryFrames: 30,
    hitstun: 0,
    blockstun: 0,
    onHit: HIT_RESULT.THROW_HIT,
    pushback: 0,
    pushbackOnBlock: 0,
    animation: 'meleeKnee',
    animSpeed: 0.9,
    hitboxOffset: { x: 0.5, y: 1.2, z: 0 },
    hitboxSize: { x: 0.5, y: 0.5, z: 0.5 },
    comboRoutes: [],
    canChainFrom: [],
    throwMove: true,
  },

  // Aerial Kick — BackFlip, any button while airborne
  aerial_kick: {
    name: 'Aerial Kick',
    command: 'auto',
    inputDir: 'air',
    level: LEVEL.MID,
    damage: 22,
    chipDamage: 3,
    startupFrames: 12,
    activeFrames: 10,
    recoveryFrames: 48,
    hitstun: 28,
    blockstun: 14,
    onHit: HIT_RESULT.KNOCKDOWN,
    pushback: 0.4,
    pushbackOnBlock: 0.35,
    animation: 'aerialKick',
    animSpeed: 1.0,
    hitboxOffset: { x: 0.8, y: -0.3, z: 0 },
    hitboxSize: { x: 0.5, y: 0.6, z: 0.5 },
    comboRoutes: [],
    canChainFrom: [],
    forwardLunge: 0.03,
  },

  // Slide Kick — run then kick, low knockdown with forward momentum
  slide_attack: {
    name: 'Slide Kick',
    command: 'auto',
    inputDir: 'run',
    level: LEVEL.LOW,
    damage: 24,
    chipDamage: 3,
    startupFrames: 10,
    activeFrames: 8,
    recoveryFrames: 30,
    hitstun: 28,
    blockstun: 16,
    onHit: HIT_RESULT.KNOCKDOWN,
    pushback: 0.3,
    pushbackOnBlock: 0.4,
    animation: 'slideAttack',
    animSpeed: 1.2,
    hitboxOffset: { x: 0.8, y: 0.2, z: 0 },
    hitboxSize: { x: 0.7, y: 0.3, z: 0.6 },
    comboRoutes: [],
    canChainFrom: [],
    forwardLunge: 0.12,
  },

  // While Running Attack
  running_attack: {
    name: 'Shoulder Tackle',
    command: 'auto',
    inputDir: 'run',
    level: LEVEL.MID,
    damage: 28,
    chipDamage: 4,
    startupFrames: 8,
    activeFrames: 6,
    recoveryFrames: 22,
    hitstun: 30,
    blockstun: 18,
    onHit: HIT_RESULT.KNOCKDOWN,
    pushback: 0.5,
    pushbackOnBlock: 0.6,
    animation: 'heavyPunch',
    animSpeed: 1.3,
    hitboxOffset: { x: 0.6, y: 1.0, z: 0 },
    hitboxSize: { x: 0.6, y: 0.6, z: 0.5 },
    comboRoutes: [],
    canChainFrom: [],
    forwardLunge: 0.08,
  },
};
