/**
 * Build-time character source list — input FBXs the pipeline ingests.
 * Runtime metadata (scale, display name, thumbnails, etc.) lives in
 * src/fighter/characters.ts and is applied at runtime, not baked into GLBs.
 *
 * Each entry produces `public/assets/models/<id>.glb` via `bun run build:character`.
 *
 * Requirements for the input FBX:
 *   - Mixamo-rigged (bone names prefixed with `mixamorig:`)
 *   - T-pose action available (Mixamo's `mixamo.com` action at frame 1)
 *   - Weights auto-generated by mixamo.com
 */

export interface CharacterSource {
  /** Output filename (without extension) — becomes public/assets/models/<id>.glb */
  id: string;
  /** Absolute path to the Mixamo FBX */
  fbx: string;
}

export const CHARACTERS: CharacterSource[] = [
  {
    id: 'beano',
    fbx: `${process.env.HOME}/tmp/Beano-T-mixamo.fbx`,
  },
  {
    id: 'mita',
    fbx: `${process.env.HOME}/Downloads/Mita-T-posed.fbx`,
  },
];
